# AUTOGENERATED! DO NOT EDIT! File to edit: Predict_for_app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'classify']

# %% Predict_for_app.ipynb 1
from fastai.vision.all import *
import timm

# %% Predict_for_app.ipynb 2
import gradio as gr

# %% Predict_for_app.ipynb 3
learn = load_learner('bird_classifier_convnext_base_989.pkl')
categories = learn.dls.vocab

# %% Predict_for_app.ipynb 5
def classify(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% Predict_for_app.ipynb 8
image = gr.inputs.Image(shape=(128,128))
label = gr.outputs.Label()
examples = ['sparrow.jpeg', 'robin.jpeg']

intf = gr.Interface(fn=classify, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
